###

GET https://api.coingecko.com/api/v3/ping
x-cg-demo-api-key: {{coinGeckoApiKey}}


###
GET https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&per_page=10&page=1


### COIN DATA BY ID
GET https://api.coingecko.com/api/v3/coins/ethereum


### Historical Data
GET https://api.coingecko.com/api/v3/coins/ethereum/market_chart?vs_currency=usd&days=30

